# Generated by Django 4.0.1 on 2022-01-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greatreads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='release',
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
