# Generated by Django 4.0.1 on 2022-01-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greatreads', '0002_remove_book_release_alter_author_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
