# Generated by Django 4.0.1 on 2022-01-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greatreads', '0003_book_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release',
            field=models.IntegerField(null=True),
        ),
    ]
