# Generated by Django 4.0.1 on 2022-01-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greatreads', '0004_alter_book_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
